### ISSUE TITLE
Ask for advice

### ISSUE THREAD

**Issue by yyy33** [cshuaimin/ssr.nvim#1]
Is there any advantage to this writing, I often see this writing.Returns an empty table, not the ui table itself
https://github.com/cshuaimin/ssr.nvim/blob/e54d9bda5996dadd66c8ec91960283f7c7696cdd/lua/ssr.lua#L49

**Comment by cshuaimin** [comment]
The ui table itself is the "class", template of instance. Returning ui itself will result in all instances refer to the same table. Here we need to "instantiate" the class to an object, so creating a new table.

**Comment by cshuaimin** [comment]
And the returned table does not need to be empty. You can set initial fields to it just like what we do in a regular constructor.

**Comment by yyy33** [comment]
> And the returned table does not need to be empty. You can set initial fields to it just like what we do in a regular constructor.

Thanks for the reply, that's a good tip

**Comment by yyy33** [comment]
> And the returned table does not need to be empty. You can set initial fields to it just like what we do in a regular constructor.

and Where do you see this `get_buf_lang` function, I don't see it described in `: help nvim-treesitter` and `:help treesitter`

https://github.com/cshuaimin/ssr.nvim/blob/e54d9bda5996dadd66c8ec91960283f7c7696cdd/lua/ssr.lua#L55

**Comment by cshuaimin** [comment]
I don’t know why it’s not in help doc, the source is here: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/parsers.lua#L1370

**Comment by yyy33** [comment]
> I don’t know why it’s not in help doc, the source is here: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/parsers.lua#L1370

Oh, thanks for the help, very nice project

**Comment by cshuaimin** [comment]
Thanks! Feel free to ask any questions, and I will answer you if I know it.
