### ISSUE TITLE
Error executing lua: invalid key: title_pos

### ISSUE THREAD

**Issue by neanias** [cshuaimin/ssr.nvim#12]
When trying to replace a pattern that matches multiple AST nodes, I get the following error. I've also seen it complain about `title` being an invalid key. I'm running Neovim v0.8.1 and as far as I can tell `vim.api.nvim_open_win()` doesn't accept `title` or `title_pos` as config options in that version.

```
E5108: Error executing lua: ~/.local/share/nvim/lazy/ssr.nvim/lua/ssr.lua:258: invalid key: title_pos
stack traceback:
	[C]: in function 'nvim_open_win'
	~/.local/share/nvim/lazy/ssr.nvim/lua/ssr.lua:258: in function 'open_confirm_win'
	~/.local/share/nvim/lazy/ssr.nvim/lua/ssr.lua:335: in function 'func'
	~/.local/share/nvim/lazy/ssr.nvim/lua/ssr.lua:90: in function <~/.local/share/nvim/lazy/ssr.nvim/lua/ssr.lua:89>
```

**Comment by dinhmai74** [comment]
I'm facing the same issue with nvim 0.9, anyway to resolve it yet @neanias ?

**Comment by cshuaimin** [comment]
The title key is added in nvim 0.9, @dinhmai74 can you see the title key in `:h nvim_open_win`? Maybe you are not using latest nightly version?

**Comment by neanias** [comment]
@cshuaimin if this plug-in requires Neovim nightly/0.9, could you add that to the README?
