### ISSUE TITLE
Repo Is Unlicensed

### ISSUE THREAD

**Issue by jls83** [cshuaimin/ssr.nvim#7]
Would you mind adding a license? I'd love to use this at work, but I'd rather not use unlicensed software if possible. Thanks!

**Comment by cshuaimin** [comment]
I'm not sure which license to choose, do you have any suggestions?

**Comment by jls83** [comment]
I've seen a number of Neovim-related projects use the MIT License (including [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) and [packer.nvim](https://github.com/wbthomason/packer.nvim)). I'd suggest taking a look at [Choose a License](https://choosealicense.com/) for a nice guide as to what's available.

**Comment by jls83** [comment]
Thank you @cshuaimin !
